# -- 코드를 입력하세요 , count(*) as USERS
SELECT YEAR(s.SALES_DATE) as YEAR, MONTH(s.SALES_DATE) as MONTH, i.GENDER, count(DISTINCT(s.USER_ID)) as USERS
FROM USER_INFO i, ONLINE_SALE s
WHERE i.USER_ID = s.USER_ID and i.GENDER is not NULL
GROUP BY DATE_FORMAT(s.SALES_DATE, '%Y %M'), i.GENDER
ORDER BY YEAR, MONTH, i.GENDER;


