select d.ROUTE, CONCAT(ROUND(SUM(d.D_BETWEEN_DIST),1),'km') as TOTAL_DISTANCE, CONCAT(ROUND(avg(d.D_BETWEEN_DIST), 2), 'km') as AVERAGE_DISTANCE
from SUBWAY_DISTANCE d
group by d.ROUTE 
order by ROUND(SUM(d.D_BETWEEN_DIST),1) desc;