-- 코드를 입력하세요
SELECT a.ANIMAL_TYPE, COUNT(*) as count
FROM ANIMAL_INS a
GROUP BY a.ANIMAL_TYPE
ORDER BY a.ANIMAL_TYPE asc;

# SELECT a.ANIMAL_TYPE, count(a.ANIMAL_ID)
# FROM ANIMAL_INS a
# WHERE a.ANIMAL_TYPE = "Cat";