-- 코드를 작성해주세요
SELECT COUNT(i.FISH_TYPE) as FISH_COUNT, n.FISH_NAME 
FROM FISH_INFO i, FISH_NAME_INFO n
WHERE i.FISH_TYPE = n.FISH_TYPE
GROUP BY n.FISH_NAME, i.FISH_TYPE
ORDER BY FISH_COUNT DESC;
     
# SELECT i.FISH_TYPE, 
#     (SELECT COUNT(FISH_TYPE) as FISH_COUNT 
#      FROM FISH_INFO
#      GROUP BY FISH_TYPE
#     )
# FROM FISH_INFO i
# GROUP BY i.FISH_TYPE, i.ID;

# SELECT n.FISH_NAME
# FROM FISH_INFO i, FISH_NAME_INFO n
# WHERE i.FISH_TYPE = n.FISH_TYPE
# and (WHERE i.FISH_TYPE)
