SELECT *
FROM (
    SELECT u.USER_ID as USER_ID, u.NICKNAME as NICKNAME, SUM(b.PRICE) as PRICE
    FROM USED_GOODS_BOARD b, USED_GOODS_USER u
    WHERE b.WRITER_ID = u.USER_ID and b.STATUS = 'DONE'
    GROUP BY u.USER_ID
) c
WHERE c.PRICE >= 700000
ORDER BY  c.PRICE;
;